services:
  bot:
    image: oshinoko/flux-bot:latest
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes

volumes:
  redis-data: